services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: lunch_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 199887766
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
